### ISSUE TITLE
g.factor(['a'], potential=np.array([0.3, 0.7])) is wrong?

### ISSUE THREAD

**Issue by HuiQiu1982** [mbforbes/py-factorgraph#1]
In the example,  condition probability should be g.factor(['b'], potential=np.array([0.x, 0.x, 0.x])), not  factor 'a',  right ?

**Comment by mbforbes** [comment]
Could you please give some more details for why it seems wrong?

**Comment by HuiQiu1982** [comment]
g.factor(['b', 'a'], potential below means p(a|b) ?  if so , to get p(a) the equation should be pa = sum(p(a|b)*p(b)) ? so p(b) should be known first.  i'm not sure, please corret me, thanks~

```python
g.rv('a', 2)
g.rv('b', 3)

# Add some factors, unary and binary
g.factor(['a'], potential=np.array([0.3, 0.7]))
g.factor(['b', 'a'], potential=np.array([
        [0.2, 0.8],
        [0.4, 0.6],
        [0.1, 0.9],
]))
```

**Comment by HuiQiu1982** [comment]
@mbforbes ,   
        hello, would you like to help me about this doubt ?

Or, would you provide me another complete example of this code? i want to learn and then use it in my project. Thanks so much~

**Comment by mbforbes** [comment]
Hi @HuiQiu1982, I'm sorry for my slow reply to this.

From what I can remember, the potentials in the examples are not meant to illustrate any situation in particular (e.g., `p(a|b)` or `p(b)`) — they are simply arbitrary numbers used to demonstrate how you can attach factors to random variables. 

I might recommend you come up with a simple example (e.g., provide a unary factor on `b` instead of `a`, as you were suggesting), see what you come up with on paper, and then see if the algorithm produces the same thing. You could, for example, google around for a simple graphical model example and see if you can encode it in a factor graph. Just a thought!

**Comment by mbforbes** [comment]
@HuiQiu1982 I'm working towards a deadline soon, but I can come up with a small example for you on Wednesday, May 23. Feel free to post anything you come up with in the mean time and I can take a look then as well!

**Comment by HuiQiu1982** [comment]
Thanks so much~, i'm trying to understand the code of  another project now, so that i can get what the means of potential better. Unfortunately, the new project deal with marginal probability using exhaustive method, not factor graph. So, maybe, finally  i will return to you code again.  
its example as below, easy to understand and fit my expectation.
https://github.com/brettc/causalinfo/blob/master/notebooks/wet_grass.ipynb

**Comment by mbforbes** [comment]
Phew, I'm sorry for taking so long to get back to you! I kept hoping I'd get time to make some more examples, but I just don't think I'm going to :-(

If you're interested in doing Bayesian modeling, I think I'd suggest you go with something like you linked above, where you can more easily encode causal relations. This library is more meant for constructing arbitrary factor graphs without performing the kind of structured inference you do when your graph is a Bayes net. 

The best thing I can recommend to see whether this fits your needs is to check out the factor graph resources I posted on the readme. For those kinds of problems this might be a good fit, but for more Bayes stuff, there are likely better tools!

**Comment by mbforbes** [comment]
(Going to close this for now --- feel free to open new issues for more questions. Thanks!)
