### ISSUE TITLE
potential param of fg.Graph().factor() and porting to pomegranate

### ISSUE THREAD

**Issue by mercicle** [mbforbes/py-factorgraph#4]
Hi @mbforbes @hyanwong ,
I'm wondering if you could comment on how to port (to do runtime analysis) of a fg model with the library pomegranate. Specifically, if we take your example in README how would you port that to a BayesianNetwork() in pomegranate to do LBP for comparison? The crux of the issue is the interpretation of the `potential` param for the `fg.Graph().factor()`, can you explain and perhaps comment on the porting (here is an example of pomegranate interface: https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html).
Thanks!

**Comment by mbforbes** [comment]
Hey @mercicle, Pomegranate looks awesome, but I have no experience with it, so I won't be able to offer any help with porting :-(

**Comment by mbforbes** [comment]
In case it helps, the tutorial linked from the readme (https://www.cs.cmu.edu/~mgormley/bp-tutorial/) is a great resource for understanding how potentials work in factor graphs — or it might be helpful to check out more foundational factor graph material. I'll leave this issue open for a week in case others see it and have comments!

**Comment by mbforbes** [comment]
Closing for now — good luck!
