### ISSUE TITLE
Python 3 on pypi?

### ISSUE THREAD

**Issue by ttamg** [mbforbes/py-factorgraph#8]
Hi there

Any plans to release the Python 3 version of this onto PyPI?  I believe the PyPI version is still on 0.0.2 from 2017 which looks like Python 2 to me?

Thanks a lot

**Comment by mbforbes** [comment]
Good idea! I didn't know whether anyone was actually using this 😅 Happy to update, will look into remembering how pypi works soon

**Comment by mbforbes** [comment]
This is done at https://pypi.org/project/factorgraph/

Please let me know if you run into any issues!
